"""Build the Pareto-frontier leaderboard from results/*.json."""

from __future__ import annotations

import json
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
RESULTS = REPO / "results"
BOARD = REPO / "LEADERBOARD.md"

# The size targets the frontier is reported against.
BUCKETS = [
    (256, "≤ 256 B"),
    (1024, "≤ 1 KB"),
    (4096, "≤ 4 KB"),
    (10240, "≤ 10 KB"),
    (51200, "≤ 50 KB"),
    (102400, "≤ 100 KB"),
    (float("inf"), "> 100 KB"),
]


def load_results() -> list[dict]:
    if not RESULTS.exists():
        return []
    rows = [json.loads(p.read_text()) for p in sorted(RESULTS.glob("*.json"))]
    return [r for r in rows if r.get("split") == "test"]


def pareto(rows: list[dict]) -> list[dict]:
    """Points not dominated by a smaller-or-equal artifact with >= accuracy."""
    out = []
    for r in rows:
        if not any(
            o is not r
            and o["description_length"] <= r["description_length"]
            and o["accuracy"] >= r["accuracy"]
            and (o["description_length"], -o["accuracy"])
            < (r["description_length"], -r["accuracy"])
            for o in rows
        ):
            out.append(r)
    return sorted(out, key=lambda r: r["description_length"])


def _fmt_size(n: int) -> str:
    return f"{n:,} B" if n < 10240 else f"{n / 1024:.1f} KB"


def _row(r: dict) -> str:
    s = r["size"]
    train = f"{r['train_seconds']:.0f}s" if r.get("train_seconds") else "—"
    warn = " ⚠️" if not r.get("self_contained", True) else ""
    return (
        f"| `{r['name']}`{warn} | **{_fmt_size(r['description_length'])}** | "
        f"{r['accuracy'] * 100:.2f}% | {s['raw']:,} | {s['gzip']:,} | "
        f"{s['xz']:,} | {r.get('method', '')} | {train} |"
    )


HEADER = (
    "| model | size | accuracy | raw | gzip | xz | method | train |\n"
    "|---|---:|---:|---:|---:|---:|---|---:|"
)


def render(rows: list[dict]) -> str:
    if not rows:
        return "# tiny-cifar leaderboard\n\n_No results yet._\n"

    front = pareto(rows)
    front_names = {r["name"] for r in front}
    best = max(rows, key=lambda r: r["accuracy"])

    L = [
        "# tiny-cifar leaderboard",
        "",
        "Smallest CIFAR-10 classifiers by **description length** — bytes of the",
        "shortest shippable encoding of a self-contained artifact (see",
        "`tinycifar/artifact.py`). Accuracy is top-1 on the full 10,000-image",
        "test set. Generated by `python -m tinycifar.leaderboard`; do not edit.",
        "",
        f"{len(rows)} artifacts · {len(front)} on the frontier · "
        f"best accuracy {best['accuracy'] * 100:.2f}% (`{best['name']}`) · "
        f"smallest {_fmt_size(min(r['description_length'] for r in rows))}",
        "",
        "## Pareto frontier",
        "",
        "Points no other artifact beats on both size and accuracy.",
        "",
        HEADER,
    ]
    L += [_row(r) for r in front]

    L += ["", "## Best at each size target", ""]
    L += [HEADER]
    prev = 0
    for cap, label in BUCKETS:
        under = [r for r in rows if prev < r["description_length"] <= cap]
        prev = cap
        if under:
            b = max(under, key=lambda r: r["accuracy"])
            L.append(_row(b).replace("| `", f"| {label} — `", 1))

    rest = [r for r in sorted(rows, key=lambda r: r["description_length"])
            if r["name"] not in front_names]
    if rest:
        L += ["", "## Dominated entries", "", HEADER]
        L += [_row(r) for r in rest]

    L += [
        "",
        "---",
        "",
        "⚠️ marks an artifact that failed the self-containment check — its true",
        "description length is larger than reported.",
        "",
    ]
    return "\n".join(L)


def main() -> int:
    rows = load_results()
    BOARD.write_text(render(rows))
    print(f"wrote {BOARD} ({len(rows)} results, {len(pareto(rows))} on frontier)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
